---
- name: Add stable chart repo redis
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
    repo_state: "present"
    force_update: true
  with_items:
    - {name: "bitnami", url: "https://charts.bitnami.com/bitnami"}

- name: Copy values
  ansible.builtin.copy:
    src: '/source/config/_3_redis/values.yaml'
    dest: '/tmp/values_redis.yaml'
    mode: "0640"

- name: Remove redis
  kubernetes.core.helm:
    name: redis
    chart_ref: bitnami/redis
    release_namespace: storage
    create_namespace: true
    state: absent
    wait: true
    values_files:
      - /tmp/values_redis.yaml

- name: Install redis
  kubernetes.core.helm:
    name: redis
    chart_ref: bitnami/redis
    release_namespace: storage
    create_namespace: true
    state: present
    wait: true
    values_files:
      - /tmp/values_redis.yaml
