---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-cron-script
  namespace: storage
data:
  backup.sh: |
    #!/usr/bin/env ash
    mkdir -p /tmp/backup/etcd
    mkdir -p /tmp/backup/pgsql
    etcdctl snapshot save /tmp/backup/etcd/etcd-backup-$(date '+%Y-%m-%d-%H-%M').db \
    --cacert="/tmp/cm-client-etcd-tls/ca.crt" \
    --cert="/tmp/cm-client-etcd-tls/tls.crt" \
    --key="/tmp/cm-client-etcd-tls/tls.key" \
    --endpoints="https://192.168.2.2:2381"

    export PGPASSWORD="$(cat /tmp/pgsql-secrets/postgres-password)"
    pg_dumpall --clean --if-exists --load-via-partition-root --quote-all-identifiers \
    --host=postgresql-primary.storage.svc --port=5432 --username=postgres \
    --file=/tmp/backup/pgsql/pg_dumpall-$(date '+%Y-%m-%d-%H-%M').pgdump;

    (find /tmp/backup/etcd/ -mindepth 1 -mmin +1440 | xargs rm) &>/dev/null || true;
    (find /tmp/backup/pgsql/ -mindepth 1 -mmin +1440 | xargs rm) &>/dev/null || true;
  minio-backup.sh: |
    #!/usr/bin/env ash
    mkdir -p /tmp/backup/minio/
    tar -zcf "/tmp/backup/minio/$(date '+%Y-%m-%d_%H-%M').tar" -C /source/minio/ .
    (find /tmp/backup/minio/ -mindepth 1 -mmin +1440 | xargs rm) &>/dev/null || true;

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-storage
  namespace: storage
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          nodeSelector:
            kubernetes.io/hostname: "storage01"
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
          containers:
            - name: backup
              image: ghcr.io/fzen475/multitool:latest
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /entrypoint.sh
                  name: backup-cron-script
                  subPath: backup.sh
                  readOnly: true
                - name: backup
                  mountPath: /tmp/backup
                - name: cm-client-etcd-tls
                  mountPath: /tmp/cm-client-etcd-tls
                  readOnly: true
                - name: pgsql-secrets
                  mountPath: /tmp/pgsql-secrets
                  readOnly: true
          dnsPolicy: ClusterFirst
          volumes:
            - name: backup-cron-script
              configMap:
                defaultMode: 0744
                name: backup-cron-script
                items:
                  - key: backup.sh
                    path: backup.sh
            - name: backup
              persistentVolumeClaim:
                claimName: backup-pvc
            - name: cm-client-etcd-tls
              secret:
                defaultMode: 420
                secretName: cm-client-etcd-tls
            - name: pgsql-secrets
              secret:
                defaultMode: 420
                secretName: pgsql-secrets

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-minio-storage
  namespace: storage
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          nodeSelector:
            kubernetes.io/hostname: "storage01"
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
          containers:
            - name: backup-minio
              image: ghcr.io/fzen475/multitool:latest
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /entrypoint.sh
                  name: backup-cron-script
                  subPath: minio-backup.sh
                  readOnly: true
                - name: backup
                  mountPath: /tmp/backup
                - name: minio-data
                  mountPath: /source/minio
          dnsPolicy: ClusterFirst
          volumes:
            - name: backup-cron-script
              configMap:
                defaultMode: 0744
                name: backup-cron-script
                items:
                  - key: minio-backup.sh
                    path: minio-backup.sh
            - name: backup
              persistentVolumeClaim:
                claimName: backup-pvc
            - name: minio-data
              hostPath:
                path: /minio-data/
                type: Directory



