
- name: Add stable chart repo postgresql
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
    repo_state: "present"
    force_update: true
  with_items:
    - {name: "bitnami", url: "https://charts.bitnami.com/bitnami"}
    - { name: "runix", url: "https://helm.runix.net/" }

#- name: configmap pgsql-conf
#  kubernetes.core.k8s:
#    state: absent
#    namespace: storage
#    definition:
#      apiVersion: v1
#      kind: ConfigMap
#      metadata:
#        name: pgsql-conf
#
#- name: configmap pgsql-conf
#  kubernetes.core.k8s:
#    state: present
#    namespace: storage
#    definition:
#      apiVersion: v1
#      kind: ConfigMap
#      metadata:
#        name: pgsql-conf
#      data:
##        postgresql.conf: "{{ lookup('ansible.builtin.file', '/source/config/_2_pgsql/postgresql.conf') }}"
#        pg_hba.conf: "{{ lookup('ansible.builtin.file', '/source/config/_2_pgsql/pg_hba.conf') }}"
#
#- name: Copy values
#  ansible.builtin.copy:
#    src: '/source/config/_2_pgsql/_1_values-pgsql.yaml'
#    dest: '/tmp/values_pgsql.yaml'
#    mode: "0640"
#
#- name: Remove postgresql
#  kubernetes.core.helm:
#    name: postgresql
#    chart_ref: bitnami/postgresql
#    release_namespace: storage
#    create_namespace: true
#    state: absent
#    wait: true
#    values_files:
#      - /tmp/values_pgsql.yaml
#
#- name: Install postgresql
#  kubernetes.core.helm:
#    name: postgresql
#    chart_ref: bitnami/postgresql
#    release_namespace: storage
#    create_namespace: true
#    state: present
#    wait: false
#    values_files:
#      - /tmp/values_pgsql.yaml

- name: Creating servers_tmp
  ansible.builtin.set_fact:
    servers_tmp: "{{ lookup('ansible.builtin.file', '/source/config/_2_pgsql/pgadmin_servers.json') | replace('\n','')  }}"

- name: ConfigMap pgadmin_servers
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: pgadmin4-servers
        namespace: storage
      data:
        servers.json: "{{ servers_tmp | to_json }}"

- name: Copy values
  ansible.builtin.copy:
    src: '/source/config/_2_pgsql/_2_values-pgadmin.yaml'
    dest: '/tmp/values_pgadmin.yaml'
    mode: "0640"

- name: Remove pgadmin4
  kubernetes.core.helm:
    name: pgadmin4
    chart_ref: runix/pgadmin4
    release_namespace: storage
    create_namespace: true
    state: absent
    wait: true
    values_files:
      - /tmp/values_pgadmin.yaml

- name: Install pgadmin4
  kubernetes.core.helm:
    name: pgadmin4
    chart_ref: runix/pgadmin4
    release_namespace: storage
    create_namespace: true
    state: present
    wait: false
    values_files:
      - /tmp/values_pgadmin.yaml