- hosts: control_main
  become: true
  tasks:

#    - name: Install init.
#      ansible.builtin.include_tasks: ./_0_init/_1_install.yaml

#    - name: Install minio.
#      ansible.builtin.include_tasks: ./_1_minio/_1_install.yaml

#    - name: Install pgsql.
#      ansible.builtin.include_tasks: ./_2_pgsql/_1_install.yaml
#
#    - name: Install redis.
#      ansible.builtin.include_tasks: ./_3_redis/_1_install.yaml

    - name: Install kafka.
      ansible.builtin.include_tasks: ./_4_kafka/_1_install.yaml